//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: AppFrameBase.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "AppFrameBase.h"


// Declare the bitmap loading function
extern void wxC2843InitBitmapResources();

static bool bBitmapLoaded = false;


AppFrameBase::AppFrameBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC2843InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    main_sizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(main_sizer);
    
    m_panel5 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    main_sizer->Add(m_panel5, 0, wxALL, WXC_FROM_DIP(5));
    
    boxSizer7 = new wxBoxSizer(wxVERTICAL);
    m_panel5->SetSizer(boxSizer7);
    
    boxSizer41 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer7->Add(boxSizer41, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    boxSizer41->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    ExitButton = new wxButton(m_panel5, wxID_ANY, _("Exit"), wxDefaultPosition, wxDLG_UNIT(m_panel5, wxSize(-1,-1)), 0);
    wxFont ExitButtonFont(11, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, false, wxT("Segoe UI"));
    ExitButton->SetFont(ExitButtonFont);
    
    boxSizer41->Add(ExitButton, 0, wxALL, WXC_FROM_DIP(5));
    
    MinimizeButton = new wxButton(m_panel5, wxID_ANY, _("Minimize"), wxDefaultPosition, wxDLG_UNIT(m_panel5, wxSize(-1,-1)), 0);
    wxFont MinimizeButtonFont(11, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, false, wxT("Segoe UI"));
    MinimizeButton->SetFont(MinimizeButtonFont);
    
    boxSizer41->Add(MinimizeButton, 0, wxALL, WXC_FROM_DIP(5));
    
    boxSizer41->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    SetName(wxT("AppFrameBase"));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    // Connect events
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(AppFrameBase::OnClose), NULL, this);
    ExitButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AppFrameBase::OnExit), NULL, this);
    MinimizeButton->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AppFrameBase::OnMinimize), NULL, this);
    
}

AppFrameBase::~AppFrameBase()
{
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(AppFrameBase::OnClose), NULL, this);
    ExitButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AppFrameBase::OnExit), NULL, this);
    MinimizeButton->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AppFrameBase::OnMinimize), NULL, this);
    
}
