//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: AppFrameBase.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _DESKTOP_TEMPLATES_APPFRAMEBASE_BASE_CLASSES_H
#define _DESKTOP_TEMPLATES_APPFRAMEBASE_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class AppFrameBase : public wxDialog
{
protected:
    wxBoxSizer* main_sizer;
    wxPanel* m_panel5;
    wxBoxSizer* boxSizer7;
    wxBoxSizer* boxSizer41;
    wxButton* ExitButton;
    wxButton* MinimizeButton;

protected:
    virtual void OnClose(wxCloseEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMinimize(wxCommandEvent& event) { event.Skip(); }

public:
    wxButton* GetExitButton() { return ExitButton; }
    wxButton* GetMinimizeButton() { return MinimizeButton; }
    wxPanel* GetPanel5() { return m_panel5; }
    AppFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("wxWidgets Template"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~AppFrameBase();
};

#endif
